[package]
name = "tetris"
version = "0.1.0"
authors = ["jamulan <jamulan@ijuggle5.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = ""
image = ""